FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_URL
ARG VITE_FAMILY_CODE

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_FAMILY_CODE=$VITE_FAMILY_CODE

COPY package*.json ./
RUN npm config set strict-ssl false && npm install

COPY . .
RUN npm run build

# --- Nginx sirve el build ---
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
