# Generated by Django 5.0.6 on 2026-05-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('image', models.URLField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portada de mes',
                'verbose_name_plural': 'Portadas de mes',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
