# Generated by Django 5.0.6 on 2026-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_monthcover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthcover',
            name='image',
        ),
        migrations.AddField(
            model_name='monthcover',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
